import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import { Suspense } from 'react'

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app'
// }

export const metadata = {
  title: {
    default: 'PokeNext 1.0',
    template: '%s | PokeNext 1.0'
  },
  description: 'Pokedex created with Next 13 and React 18',
  icons: {
    icon: '/favicon.ico',
    shortcut: '/favicon.ico',
    apple: '/favicon.ico',
    other: {
      rel: 'apple-touch-icon-precomposed',
      url: '/favicon.ico'
    }
  },
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1
  }
}

export default function RootLayout({ children }) {
  return (
    // <html lang='en'>
    //   <body>{children}</body>
    // </html>
    <html lang='en'>
      <body>
        <Suspense fallback={<div>Loading</div>}>
          {/* The problem with hydration resolve with suspense  */}
          <Navbar />
          <main className='main-container'>{children}</main>
          <Footer />
        </Suspense>
      </body>
    </html>
  )
}
